[build-system]
requires = [
    "setuptools>=58",
    "wheel",
    "cmake~=3.20.5",
    "ninja; sys_platform != 'win32' and platform_machine != 'arm64'",
]
build-backend = "setuptools.build_meta"


[tool.cibuildwheel]
skip = "*-win32 *-manylinux_i686 pp* cp36-* *-musllinux_*"

build-frontend = "build"

test-extras = ["test"]
test-command = "pytest {project}"

manylinux-x86_64-image = "ghcr.io/jessefarebro/manylinux2014-vcpkg"
