name: Build ALE
on:
  push:
    tags-ignore:
      - "*.*"
    paths-ignore:
      - "docs/**"
    branches:
      - "*"
  pull_request:
    branches:
      - "*"

jobs:
  presubmit:
    name: Presubmit checks
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: ./scripts/presubmit.sh


  build:
    name: Build ALE on ${{ matrix.config.os }}
    needs: presubmit
    defaults:
      run:
        shell: bash
    strategy:
      matrix:
        config: [
          {"os": "ubuntu-latest", "triplet": "x64-linux-mixed"},
          {"os": "windows-latest", "triplet": "x64-windows"},
          {"os": "macos-latest", "triplet": "x64-osx-mixed"}
        ]
    env:
      VCPKG_DEFAULT_TRIPLET: ${{ matrix.config.triplet }}
    runs-on: ${{ matrix.config.os }}

    steps:
    - uses: actions/checkout@v2

    - uses: actions/setup-python@v2
      with:
        python-version: "3.x"

    - name: Install pip dependencies
      run: |
        python -m pip install gym pytest cmake==3.20.5

    - name: Configure ALE
      run: |
        cmake --version
        mkdir build; cd build
        cmake ../ -DSDL_SUPPORT=ON -DPython3_EXECUTABLE=$(which python)

    - name: Build ALE
      working-directory: ./build
      run: cmake --build . --config Debug --parallel 2

    - name: Test ALE
      working-directory: ./build
      run: ctest -C Debug --progress -VV
